services:
  ros2zed:
    container_name: zed2_driver
    image: zed2_driver:jazzy-zed
    build:
      context: .
      dockerfile: Dockerfile

    # Stereolabs addressï¼šGPU + privileged + X11 (GUI of rivz) + /dev + NVIDIA_DRIVER_CAPABILITIES
    # :contentReference[oaicite:3]{index=3}
    gpus: all
    privileged: true
    network_mode: "host"
    ipc: "host"
    pid: "host"

    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_DRIVER_CAPABILITIES=all
      - ROS_DOMAIN_ID=42
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - QT_X11_NO_MITSHM=1

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev:/dev
      - /dev/shm:/dev/shm

      # to make ZED resources/settings persistent
      - /usr/local/zed/resources:/usr/local/zed/resources:rw
      - /usr/local/zed/settings:/usr/local/zed/settings:rw

    stdin_open: true
    tty: true
    restart: unless-stopped
    command: ["bash", "-lc", "sleep infinity"]
